apiVersion: v1
data:
  application.properties: |-
    spring.datasource.url=jdbc:postgresql://tododb:5432/todo
    spring.jpa.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
    management.endpoints.web.exposure.include=*
    demo.env="I'm running on openshift"
kind: ConfigMap
metadata:
  name: java-demo
