apiVersion: v1
data:
  database-name: dG9kbw==
  database-password: b3BlbnNoaWZ0MTIz
  database-user: dG9kbw==
kind: Secret
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  labels:
    app: postgresql-ephemeral
    app.kubernetes.io/component: postgresql-ephemeral
    app.kubernetes.io/instance: postgresql-ephemeral
    template: postgresql-ephemeral-template
type: Opaque
