apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresql-ephemeral
    app.kubernetes.io/component: postgresql-ephemeral
    app.kubernetes.io/instance: postgresql-ephemeral
    template: postgresql-ephemeral-template
spec:
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    name: tododb
  sessionAffinity: None
  type: ClusterIP
